WebApp/FairyDustFriends.WebApp/Models/FriendViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FairyDustFriends.WebApp.Models
{
    public class FriendModel
    {
        public String Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public String FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public String LastName { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "E-mail invalid!")]
        [Display(Name = "Email")]
        public String Email { get; set; }

        [Required]
        [Display(Name = "Phone")]
        [StringLength(maximumLength:14, MinimumLength =8)]        
        public String Phone { get; set; }

        [Required]
        [Display(Name = "Birthday")]        
        public String Birthday { get; set; }
    }
}

WebApp/FairyDustFriends.WebApp/Controllers/FriendController.cs
using FairyDustFriends.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace FairyDustFriends.WebApp.Controllers
{
    public class FriendController : Controller
    {
        HttpClient _client;

        public FriendController()
        {
            _client = new HttpClient();
            _client.BaseAddress = new Uri(WebConfigurationManager.AppSettings["AzureUriApiFriends"]);            
            _client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Friend
        public ActionResult Index()        {

            var friends = _client.GetAsync("api/friend").Result.Content.ReadAsAsync<IEnumerable<FriendModel>>().Result;

            return View(friends);
        }

        // GET: Friend/Details/5
        public ActionResult Details(Guid id)
        {
            FriendModel frined = new FriendModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);               
            }
            else
            {
                //Obtem Profile pelo Id
                frined = _client.GetAsync("api/friend/" + id).Result.Content.ReadAsAsync<FriendModel>().Result;
            }

            if (frined == null)
            {
                return HttpNotFound();
            }
            return View(frined);
        }

        // GET: Friend/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Friend/Create
        [HttpPost]
        public async Task<ActionResult> Create(FriendModel friendModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _client.PostAsJsonAsync<FriendModel>("api/friend", friendModel);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(friendModel);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Friend/Edit/5
        public ActionResult Edit(Guid id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            FriendModel friend = _client.GetAsync("api/friend/" + id).Result.Content.ReadAsAsync<FriendModel>().Result;

            if (friend == null)
            {
                return HttpNotFound();
            }

            return View(friend);
        }

        // POST: Friend/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(FriendModel friendModel)
        {
            if (ModelState.IsValid)
            {
                await _client.PutAsJsonAsync<FriendModel>("api/friend", friendModel);
                return RedirectToAction("Index");
            }
            return View(friendModel);
        }

        // GET: Friend/Delete/5
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FriendModel friend = _client.GetAsync("api/friend/" + id).Result.Content.ReadAsAsync<FriendModel>().Result;

            if (friend == null)
            {
                return HttpNotFound();
            }

            return View(friend);
        }

        // POST: Friend/Delete/5
        [HttpPost]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                await _client.DeleteAsync("api/friend/" + id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/FairyDustFriends.WebApp/Views/Friend/Create.cshtml
@model FairyDustFriends.WebApp.Models.FriendModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FriendModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApp/FairyDustFriends.WebApp/Views/Friend/Delete.cshtml
@model FairyDustFriends.WebApp.Models.FriendModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FriendModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Friend", FormMethod.Post)) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id);
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApp/FairyDustFriends.WebApp/Views/Friend/Details.cshtml
@model FairyDustFriends.WebApp.Models.FriendModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FriendModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApp/FairyDustFriends.WebApp/Views/Friend/Edit.cshtml
@model FairyDustFriends.WebApp.Models.FriendModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FriendModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebApp/FairyDustFriends.WebApp/Views/Friend/Index.cshtml
@model IEnumerable<FairyDustFriends.WebApp.Models.FriendModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApp/FairyDustFriends.WebApp/Views/Shared/Footer.cshtml
<footer class="footer">
    <div class="container">
        <nav>
            <p class="copyright text-center">
                ©
                <script>document.write(new Date().getFullYear())</script>
                <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
            </p>
        </nav>
    </div>
</footer>

WebApp/FairyDustFriends.WebApp/Views/Shared/Navbar.cshtml
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <a class="navbar-brand" href="@Url.Action("Index", "Friend")">TP03 Friends</a>

        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Friend")" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">@ViewBag.Title</span>
                    </a>
                </li>
                <li class="nav-item">
                    <input placeholder="Search" class="form-control form-control-sm" type="text">
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li>
                    <a href="@Url.Action("Index", "Friend")" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">@ViewBag.Title</span>
                    </a>
                </li>                                
            </ul>
        </div>
    </div>
</nav>

WebApp/FairyDustFriends.WebApp/Views/Shared/Sidebar.cshtml
<!-- 
    Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"
    Tip 2: you can also add an image using data-image tag 
-->
<div class="sidebar" data-color="blue">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="@Url.Action("Index", "Friend")" class="simple-text">
                TP03 Friends
            </a>
        </div>
        <ul class="nav">
            <li>
                <a class="nav-link active" href="@Url.Action("Index", "Friend")">
                    <i class="nc-icon nc-circle-09"></i>
                    <p>Friends</p>
                </a>
            </li>            
        </ul>
    </div>
</div>

WebApp/FairyDustFriends.WebApp/Views/Shared/_Layout.cshtml
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link rel="icon" type="image/png" href="~/Content/light_dashboard_v2/img/favicon.ico">

    <title>TP03 Friends - Template Light Bootstrap by Creative Tim</title>

    <!-- Bootstrap core CSS     -->
    <link href="~/Content/light_dashboard_v2/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="~/Content/light_dashboard_v2/css/animate.css" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="~/Content/light_dashboard_v2/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet" />

    <!-- Fonts and icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

    <link href="~/Content/light_dashboard_v2/css/pe-icon-7-stroke.css" rel="stylesheet" />
    
    <!-- Toastr -->
    <link href="~/Content/toastr/toastr.min.css" rel="stylesheet" />
    
    @RenderSection("styles", false)

</head>

<body>
    <div class="wrapper">

        <!-- Sidebar -->
        @RenderPage("~/Views/Shared/Sidebar.cshtml")
        <!-- End Sidebar -->

        <div class="main-panel">
            <!-- Navbar -->
            @RenderPage("~/Views/Shared/Navbar.cshtml")
            <!-- End Navbar -->
            <!-- Main  -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <!-- End Main -->
            <!-- Footer -->
            @RenderPage("~/Views/Shared/Footer.cshtml")
            <!-- End Footer -->

        </div>

    </div>

    <!--   Core JS Files   -->
    <script src="~/Content/light_dashboard_v2/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="~/Content/light_dashboard_v2/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/Content/light_dashboard_v2/js/core/bootstrap.min.js" type="text/javascript"></script>

    <!-- JQuery Validate -->
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <!-- Modernizr -->
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="~/Content/light_dashboard_v2/js/plugins/bootstrap-switch.js"></script>

    <!--  Google Maps Plugin    -->
    @*<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>*@

    <!--  Chartist Plugin  -->
    <script src="~/Content/light_dashboard_v2/js/plugins/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="~/Content/light_dashboard_v2/js/plugins/bootstrap-notify.js"></script>

    <!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
    <script src="~/Content/light_dashboard_v2/js/light-bootstrap-dashboard.js?v=2.0.1" type="text/javascript"></script>

    <!-- Toastr -->
    <script src="~/Scripts/toastr/toastr.min.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {

            // Javascript method's body can be found in assets/js/demos.js
            // demo.initDashboardPageCharts();
            // demo.showNotification();

        });
    </script>

    @RenderSection("scripts", false)

</body>
</html>